openapi: 3.0.0
security: []
servers:
  - url: https://spocs.getpocket.com
info:
  description: "APIs to interact with sponsored content (\"spocs\") for Firefox, while preserving privacy."
  version: '2.1'
  title: Firefox Spocs
paths:
  /spocs:
    post:
      summary: Get sponsored content
      description: Get a list of spocs based on region and pocket_id from AdZerk. The IP address is used to deduce a rough geographic region, for example "Texas" in the U.S. or "England" in the U.K. The IP is not stored or shared with AdZerk to preserve privacy.
      parameters:
        - in: query
          name: site
          schema:
            type: integer
          required: false
          description: override siteId in ad decision requests
        - in: query
          name: region
          schema:
            type: integer
          required: false
          description: override region in keywords of ad decision requests for testing
        - in: query
          name: country
          schema:
            type: integer
          required: false
          description: override country in keywords of ad decision requests for testing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpocRequest'
            examples:
              version_one:
                summary: Request from client that does not support collections, FireFox version <= 74
                value:
                  version: 1
                  consumer_key: "40249-e88c401e1b1f2242d9e441c4"
                  pocket_id: "{12345678-8901-2345-aaaa-bbbbbbcccccc}"
              version_one_collection_req:
                summary: Request for collection placements with version=1
                value:
                  version: 1
                  consumer_key: "40249-e88c401e1b1f2242d9e441c4"
                  pocket_id: "{12345678-8901-2345-aaaa-bbbbbbcccccc}"
                  placements:
                    - name: "collections-div"
                      ad_types:
                        - 1234
                      zone_ids:
                        - 5000
                      count: 10
              version_two_collection_req:
                summary: Request for collection placements with version=2
                value:
                  version: 2
                  consumer_key: "40249-e88c401e1b1f2242d9e441c4"
                  pocket_id: "{12345678-8901-2345-aaaa-bbbbbbcccccc}"
                  placements:
                    - name: "collections-div"
                      ad_types:
                        - 1234
                      zone_ids:
                        - 5000
                      count: 10
      responses:
        '200':
          description: Responds with settings and a list of spocs.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref:  "#/components/schemas/SpocFeed"
                properties:
                  settings:
                    $ref: '#/components/schemas/Settings'
                  __debug__:
                    description: Informational object returned in non-prod environments
                    type: object
                    additionalProperties: true
  /user:
    delete:
      summary: Delete a user's personal data from AdZerk
      description: Used when a user opts-out of sponsored content to delete the user's data from AdZerk.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pocket_id
              properties:
                pocket_id:
                  description: ID that uniquely identifies a session.
                  example: "{12345678-8901-2345-aaaa-bbbbbbcccccc}"
                  type: string
      responses:
        '200':
          description: Successfully deleted user data from AdZerk.

components:
  schemas:
    SpocRequest:
      type: object
      required:
        - version
        - consumer_key
        - pocket_id
        - placements
      additionalProperties: false
      properties:
        version:
          type: integer
          description: API version
          format: int32
          minimum: 1
          maximum: 2
          example: 2
        consumer_key:
          type: string
          description: Identifies that the request is coming from Firefox.
          example: 40249-e88c401e1b1f2242d9e441c4
        pocket_id:
          type: string
          description: ID that uniquely identifies a session.
          example: "{12345678-8901-2345-aaaa-bbbbbbcccccc}"
          pattern: "\\A{[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}}\\Z"
        placements:
          type: array
          items:
            $ref: "#/components/schemas/Placement"

    Placement:
      type: object
      description: https://dev.adzerk.com/reference/request
      required:
        - name
      additionalProperties: false
      properties:
        name:
          type: string
          example: spocs
          description: Corresponds to the key in the response object.
        ad_types:
          type: array
          description: https://dev.adzerk.com/docs/ad-sizes
          items:
            type: integer
            format: int32
            example: 1234
            minimum: 1
            maximum: 2147483647
        zone_ids:
          type: array
          description: https://dev.adzerk.com/docs/zones-overview
          items:
            type: integer
            format: int32
            example: 123456
            minimum: 1
            maximum: 2147483647
        count:
          type: integer
          example: 20
          minimum: 1
          maximum: 20
          description: number of spocs to return for this placement

    #### Settings ####

    Settings:
      type: object
      additionalProperties: false
      required:
        - feature_flags
        - spocsPerNewTabs
        - domainAffinityParameterSets
        - timeSegments
      properties:
        spocsPerNewTabs:
          type: integer
          minimum: 1
          example: 1
        domainAffinityParameterSets:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/DomainAffinityParameterSet'
        timeSegments:
          type: array
          items:
            $ref: '#/components/schemas/TimeSegment'
        feature_flags:
          type: object
          $ref: '#/components/schemas/FeatureFlags'

    FeatureFlags:
      type: object
      additionalProperties: false
      required:
        - spoc_v2
        - collections
      properties:
        spoc_v2:
          type: boolean
        collections:
          type: boolean

    DomainAffinityParameterSet:
      type: object
      additionalProperties: false
      required:
        - recencyFactor
        - frequencyFactor
        - combinedDomainFactor
        - perfectCombinedDomainScore
        - multiDomainBoost
        - itemScoreFactor
      properties:
        recencyFactor:
          type: number
        frequencyFactor:
          type: number
        combinedDomainFactor:
          type: number
        perfectFrequencyVisits:
          type: number
        perfectCombinedDomainScore:
          type: number
        multiDomainBoost:
          type: number
        itemScoreFactor:
          type: number

    TimeSegment:
      type: object
      additionalProperties: false
      required:
        - id
        - startTime
        - endTime
        - weightPosition
      properties:
        id:
          type: string
        startTime:
          type: integer
        endTime:
          type: integer
        weightPosition:
          example: 1

    #### Spocs ####

    SpocFeed:
      oneOf:
        - type: array
          items:
            $ref: "#/components/schemas/SpocFeedItem"
        - type: object
          additionalProperties: false
          required:
            - title
            - flight_id
          properties:
            title:
              type: string
              example: "Best of the Web"
            flight_id:
              type: integer
              example: 4321
            sponsor:
              type: string
              example: NextAdvisor
            context:
              type: string
              example: "Sponsored by NextAdvisor"
            items:
              type: array
              items:
                $ref: "#/components/schemas/SpocFeedItem"

    Shim:
      type: object
      additionalProperties: false
      properties:
        click:
          type: string
          example: "1234123asdf4tYadsfQ,xY-01BU12"
        impression:
          type: string
          example: "a0c3943asdf4tYadsf300,xY-01BU9aadc"
        delete:
          type: string
          example: "fdea123asdf4tYadsf1000,xY-01BUa654"
        save:
          type: string
          example: "4567123asdf4tYadsfQcda,xY-01BU123"

    Caps:
      type: object
      additionalProperties: false
      required:
        - lifetime
        - flight
        - campaign
      properties:
        lifetime:
          type: integer
          example: 50
        flight:
          type: object
          additionalProperties: false
          required:
            - count
            - period
          properties:
            count:
              type: integer
              example: 10
            period:
              type: integer
              description: Period in seconds
              example: 86400
        campaign:
          type: object
          additionalProperties: false
          required:
            - count
            - period
          properties:
            count:
              type: integer
              example: 10
            period:
              type: integer
              description: Period in seconds
              example: 86400

    SpocFeedItem:
      type: object
      additionalProperties: false
      properties:
        campaign_id:
          type: integer
          example: 784
        caps:
          type: object
          $ref: '#/components/schemas/Caps'
        collection_title:
          type: string
          description: Shared title if all ads are one collection
        context:
          type: string
          description: Deprecated. Use sponsor field instead.
          example: Sponsored by NextAdvisor
        cta:
          type: string
          description: Text to display on CTA button
          example: Learn more
        domain:
          type: string
          example: arstechnica.com
        domain_affinities:
          type: object
          additionalProperties:
            type: number
          example:
            vanguard.com: 0.9956
            wealthsimple.com: 0.9193
        excerpt:
          type: string
          example: Driving excerpt
        flight_id:
          type: integer
          example: 432
        id:
          type: integer
          example: 30295
        image_src:
          type: string
          example: https://img-getpocket.cdn.mozilla.net/ad.gif
        is_video:
          type: boolean
        item_score:
          type: number
          format: float
          example: 0.2
        min_score:
          type: number
          format: float
          example: 0.1
        parameter_set:
          type: string
          example: default
        personalization_models:
          type: object
          additionalProperties: true
        priority:
          type: integer
          description: The priority order. 1-100, 1 is highest priority.
          minimum: 1
          maximum: 100
        raw_image_src:
          type: string
          example: https://kevel/ad.gif
        shim:
          type: object
          $ref: '#/components/schemas/Shim'
        sponsor:
          type: string
          example: NextAdvisor
        sponsored_by_override:
          type: string
          example: NextAdvisor
        title:
          type: string
          example: Why driving is hard—even for AIs
        url:
          type: string
          example: http://url
